export const Teams = {
  EPL: [
    "Arsenal",
    "Aston Villa",
    "Bournemouth",
    "Brentford",
    "Brighton",
    "Burnley",
    "Chelsea",
    "Crystal Palace",
    "Everton",
    "Fulham",
    "Liverpool",
    "Luton Town",
    "Manchester City",
    "Manchester United",
    "Newcastle United",
    "Nottingham Forest",
    "Sheffield United",
    "Tottenham Hotspur",
    "West Ham United",
    "Wolves",
  ],

  Laliga: [
    "Athletic Club",
    "Atletico De Madrid",
    "CA Osasuna",
    "Cadiz CF",
    "Deportivo Alaves",
    "FC Barcelona",
    "Getafe CF",
    "Girona FC",
    "Granada CF",
    "Rayo Vallecano",
    "RC Celta",
    "RCD Mallorca",
    "Real Betis",
    "Real Madrid",
    "Real Sociedad",
    "Sevilla FC",
    "UD Almeria",
    "UD Las Palmas",
    "Valencia CF",
    "Villareal CF",
  ],

  Bundesliga: [
    "Augsburg",
    "Bayer Leverkusen",
    "Bayern Munich",
    "Bochum",
    "Borussia Dortmund",
    "Darmstadt",
    "Einracht Frankfurt",
    "Heidenheim",
    "Hoffenheim",
    "Koln",
    "Mainz",
    "Monchengladbach",
    "Leipzig",
    "Freiburg",
    "Stuttgart",
    "Union Berlin",
    "Wolfsburg",
    "Werder",
  ],
  SerieA: [
    "Atalanta",
    "Bologna",
    "Cagliagri",
    "Empoli",
    "Fiorentina",
    "Frosinone",
    "Genoa",
    "Inter Milan",
    "Juventus",
    "Lazio",
    "Lecce",
    "AC Milan",
    "Monza",
    "Napoli",
    "Roma",
    "Salernitana",
    "Sassuolo",
    "Torino",
    "Udinese",
    "Verona",
  ],
};
